### ISSUE TITLE
Generate topline numbers from individual programs

### ISSUE THREAD

**Issue by navarroc** [policy-design-lab/pdl-api#145] opened 2023-10-17 18:32 UTC
Once all the sub-programs are finished, we should be able to generate the topline data on the landing page from the sub programs. This will allow us to update sub-programs and automatically update the topline to reflect this.

**Comment by sandeep-ps** [comment] 2024-11-01 22:07
This is now a duplicate of https://github.com/policy-design-lab/pdl-api/issues/258 and hence I'm closing this as such.

**Closed** 2024-11-01 22:08 UTC
Labels: enhancement
